//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leave.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string dbCommandTimeout {
            get {
                return ((string)(this["dbCommandTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string enLocale {
            get {
                return ((string)(this["enLocale"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("th-TH")]
        public string thLocale {
            get {
                return ((string)(this["thLocale"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("windows-874")]
        public string DbServerEncoding {
            get {
                return ((string)(this["DbServerEncoding"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\dev\\Web\\FingerScan\\bin\\Debug")]
        public string WorkingDirectory {
            get {
                return ((string)(this["WorkingDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int EnabledTIMEATTMenuSuite {
            get {
                return ((int)(this["EnabledTIMEATTMenuSuite"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ADConnectionString {
            get {
                return ((string)(this["ADConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ADDomain {
            get {
                return ((string)(this["ADDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://porar.wingolfcloud.com:88/AdhocReports/Pages/ReportViewer.aspx?%2fmultiplu" +
            "s%2fleave%2fExport&rs:Command=Render")]
        public string LinkReportExport {
            get {
                return ((string)(this["LinkReportExport"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://porar.wingolfcloud.com:88/AdhocReports/Pages/ReportViewer.aspx?%2fmultiplu" +
            "s%2fleave%2fWorkday&rs:Command=Render")]
        public string LinkReportWorkday {
            get {
                return ((string)(this["LinkReportWorkday"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://porar.wingolfcloud.com:88/AdhocReports?%2fmultiplus%2fleave%2fLeave&rs:Com" +
            "mand=Render&rs:Format=HTML4.0&rc:toolbar=false&RequestID=")]
        public string LinkReportForm {
            get {
                return ((string)(this["LinkReportForm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://porar.wingolfcloud.com:88/AdhocReports/Pages/ReportViewer.aspx?%2fmultiplu" +
            "s%2fleave%2fNoEmail&rs:Command=Render")]
        public string LinkReportNoEmail {
            get {
                return ((string)(this["LinkReportNoEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("multiplus.co.th")]
        public string DefaultEmailDomain {
            get {
                return ((string)(this["DefaultEmailDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\multiplus.co.th\\www_aspnet\\leave_uploadfiles")]
        public string AttachFilePath {
            get {
                return ((string)(this["AttachFilePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Policy_Quota_StartingMonth {
            get {
                return ((int)(this["Policy_Quota_StartingMonth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Policy_PreDays_Maternity {
            get {
                return ((int)(this["Policy_PreDays_Maternity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Policy_PreDays_Initiation {
            get {
                return ((int)(this["Policy_PreDays_Initiation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Policy_PreDays_Celebratehullvalley {
            get {
                return ((int)(this["Policy_PreDays_Celebratehullvalley"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Policy_PreDays_Education {
            get {
                return ((int)(this["Policy_PreDays_Education"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Policy_PreDays_Sterilization {
            get {
                return ((int)(this["Policy_PreDays_Sterilization"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Policy_PreDays_Wedding {
            get {
                return ((int)(this["Policy_PreDays_Wedding"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int Policy_SickHours_MaxContinuous {
            get {
                return ((int)(this["Policy_SickHours_MaxContinuous"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal Policy_WorkHours_PerDay {
            get {
                return ((decimal)(this["Policy_WorkHours_PerDay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("multiplussmtp@gmail.com")]
        public string Policy_Bcc_LeaveApproved {
            get {
                return ((string)(this["Policy_Bcc_LeaveApproved"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int Policy_Default_MorningUntilOClock {
            get {
                return ((int)(this["Policy_Default_MorningUntilOClock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int Policy_Default_NoonBeginOClock {
            get {
                return ((int)(this["Policy_Default_NoonBeginOClock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.multiplus.co.th:81/leaveonline")]
        public string InternetBasedUrl {
            get {
                return ((string)(this["InternetBasedUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Policy_QuotaVacation_StartingMonth {
            get {
                return ((int)(this["Policy_QuotaVacation_StartingMonth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Policy_MinWorkMonths_Vacation {
            get {
                return ((int)(this["Policy_MinWorkMonths_Vacation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Policy_PreDays_Business {
            get {
                return ((int)(this["Policy_PreDays_Business"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Policy_PreDays_Vacation {
            get {
                return ((int)(this["Policy_PreDays_Vacation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int Policy_Default_MorningBeginOClock {
            get {
                return ((int)(this["Policy_Default_MorningBeginOClock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int Policy_Default_NoonUntilOClock {
            get {
                return ((int)(this["Policy_Default_NoonUntilOClock"]));
            }
        }
    }
}
